# General Config
Permissions:
  UseCustomPermissions: true    # When true Permisson will be used as the permission rerquied instead of the default permession of elitetags.access.tagname

# Tags
#- Name: Example      >>> The name of the tag
#  DisplayName: "&eExample&4&lTag"      >>> The formated tag, this is what is displayed with the %elitetags_tag_current% placeholder
#  RequiresPermission: true      >>> If users need a permission node to use the tag, if this is set to true and UseCustomPermissions is also true the permission required is the one listed bellow
#  Permisson: tags.access.example      >>> The required permission if RequiresPermission and UseCustomPermissions are both true
Tags:
    - Name: Example
      DisplayName: "&eExample&4&lTag"
      RequiresPermission: true
      Permisson: elitetags.access.exampletag