# General Config
Debug: true
Permissions:
  # Whether or not plugin uses default permissions,
  # When true Permisson will be used as the permission rerquied instead of the default permession of elitetags.access.tagname
  UseCustomPermissions: true

Customization:
  TagsMenu:
    # Name of the /tags GUI
    MenuTitle: "&e&lTag Selector"

    # Size of the /tags GUI
    # Must be one of the following: 36 45 54 ***RECOMENDED TO LEAVE AT 54 FOR BEST RESULTS***
    MenuSize: 54

    TagsItem:
      # The following placeholders can be used in the TagItems section
      # {tag_name}    >>> The name of the tag
      # {tag_displayName}    >>> The formated tag (This is what is displayed with the %elitetags_tag_current% placeholder)
      # {tag_description}    >>> The description of the tag
      # {tag_status}    >>> Displays TagStatus_UnlockedPlaceholder if the user has access to the tag, and displays TagStatus_LockedPlaceholder is the user doesn't have access to the tag.
      TagStatus_LockedPlaceholder: "&c&lLocked"
      TagStatus_UnlockedPlaceholder: "&a&lUnlocked"
      Material: "NAME_TAG"    # NOTE: BE SURE TO USE A 1.8.8 MATERIAL UNTIL I ADD MULTIPLE VERSION SUPPORT ***RECOMENDED TO LEAVE AS NAME_TAG FOR BEST RESULTS***
      DisplayName: "&6{tag_name} &eTag"     # The name of the item
      Lore:
        - "&6Description: &f{tag_description}"
        - "&6Status: {tag_status}"
    ClearTagItem:
      Material: "BARRIER"    # NOTE: BE SURE TO USE A 1.8.8 MATERIAL UNTIL I ADD MULTIPLE VERSION SUPPORT ***RECOMENDED TO LEAVE AS BARRIER FOR BEST RESULTS***
      DisplayName: "&c&lClear Tag"     # The name of the item
      Lore:
        - "&4Removes your current tag"
      Glowing: false
    NextPage:
      Material: "ARROW"    # NOTE: BE SURE TO USE A 1.8.8 MATERIAL UNTIL I ADD MULTIPLE VERSION SUPPORT ***RECOMENDED TO LEAVE AS BARRIER FOR BEST RESULTS***
      DisplayName: "&aNext Page"     # The name of the item
      Lore: []
      Glowing: false
    PreviousPage:
      Material: "ARROW"    # NOTE: BE SURE TO USE A 1.8.8 MATERIAL UNTIL I ADD MULTIPLE VERSION SUPPORT ***RECOMENDED TO LEAVE AS BARRIER FOR BEST RESULTS***
      DisplayName: "&aPrevious Page"     # The name of the item
      Lore: []
      Glowing: false
    Filler:
      Material: "STAINED_GLASS_PANE"    # NOTE: BE SURE TO USE A 1.8.8 MATERIAL UNTIL I ADD MULTIPLE VERSION SUPPORT ***RECOMENDED TO LEAVE AS BARRIER FOR BEST RESULTS***
      DisplayName: "&r "     # The name of the item
      Lore: []
      Glowing: true
      Color: 3     # Set to null if the item isn't STAINED_GLASS_PANE

#      Glass Pane Colors:
#      0 White Stained Glass Pane
#      1 Orange Stained Glass Pane
#      2 Magenta Stained Glass Pane
#      3 Light Blue Stained Glass Pane
#      4 Yellow Stained Glass Pane
#      5 Lime Stained Glass Pane
#      6 Pink Stained Glass Pane
#      7 Gray Stained Glass Pane
#      8 Light Gray Stained Glass Pane
#      9 Cyan Stained Glass Pane
#      10 Purple Stained Glass Pane
#      11 Blue Stained Glass Pane
#      12 Brown Stained Glass Pane
#      13 Green Stained Glass Pane
#      14 Red Stained Glass Pane
#      15 Black Stained Glass Pane

# Tags Config
#- Name: Example      >>> The name of the tag
#  DisplayName: "&eExample&4&lTag"      >>> The formated tag, this is what is displayed with the %elitetags_tag_current% placeholder
#  Description: "An example for how to configure tags"      >>> The description of the tag
#  RequiresPermission: true      >>> If users need a permission node to use the tag, if this is set to true and UseCustomPermissions is also true the permission required is the one listed bellow
#  ID: 1      >>> The ID of the tag, each tag must have a different id
#  Permission: tags.access.example      >>> The required permission if RequiresPermission and UseCustomPermissions are both true
Tags:
  - Name: Example
    DisplayName: "&eExample&4&lTag"
    Description: "An example for how to configure tags"
    RequiresPermission: true
    ID: 1
    Permisson: elitetags.access.exampletag
  - Name: Example2
    DisplayName: "&eExample2&4&lTag"
    Description: "An example for how to configure tags2"
    RequiresPermission: true
    ID: 2
    Permisson: elitetags.access.tagexample